name: Continuous Integration

on:
  push:
    branches:
<<<<<<< HEAD
      - "dev-*"
=======
      - 'dev-*'
>>>>>>> dev-saee1

jobs:
  merge-to-development:
    runs-on: ubuntu-latest

<<<<<<< HEAD
    permissions:
      contents: write

=======
>>>>>>> dev-saee1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

<<<<<<< HEAD
      - name: Merge developer branch into development
=======
      - name: Merge into development
>>>>>>> dev-saee1
        run: |
          git checkout development
          git merge ${{ github.ref_name }} --no-edit
          git push origin development